# Setup
title:               Seafoodfry
tagline:             'Cloud computing, Graphics, CUDA, lattice QCD, QM, and some other maths.'
description:         'Hello, this blog is a place where Im documenting a ton of interesting stuff I haveve been learning while working on lattice QCD.'
url:                 https://seafoodfry.github.io
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              seafoodfry

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.0.0
